### ISSUE TITLE
how to run this tool what command  run 

### ISSUE THREAD

**Issue by shadihh9** [GO0dspeed/spill#1]
how to run this tool what command  run

**Comment by shadihh9** [comment]
i used go run main.go ip target_ip but not run

**Comment by GO0dspeed** [comment]
Use the -h flag and you will see the CLI options. I'll update the README here soon as well.

Quick Example: `go run main.go -ip <target-ip> -port 631 -dest <your listening ip> -destport <your listening port>`
Replace the `-ip` flag with `-cidr` and enter a network in CIDR notion: IE `192.168.1.0/24` to scan an entire subnet.
Vulnerable hosts will make a POST request back to the HTTP server and you will get a printout in STDOUT.

**Comment by GO0dspeed** [comment]
Updated README with examples - thanks for the feedback!

**Comment by shadihh9** [comment]
i wait long time with run ?  its take long time

‫في الخميس، 26 سبتمبر 2024 في 8:10 م تمت كتابة ما يلي بواسطة ‪G00dspeed‬‏ <‪
***@***.***‬‏>:‬

**Comment by shadihh9** [comment]
i wait long time without  run ?  its take long time

**Comment by shadihh9** [comment]
i dont see printout in STDOUT.

**Comment by GO0dspeed** [comment]
If you don't get a response that will mean that the target likely is not vulnerable. Only vulnerable hosts will make an HTTP POST request back to your local server. This is due to the tool sending a crafted UDP packet on port 631 to the target and listening via HTTP on your host to see if that target attempts to get printer information from your host. Typically, the response is immediate from vulnerable hosts.

![image](https://github.com/user-attachments/assets/0f7fbc52-f0ee-4080-95c4-d0eb9f9a4a8f)

**Comment by shadihh9** [comment]
can sent photo output in tool

‫في الخميس، 26 سبتمبر 2024 في 8:29 م تمت كتابة ما يلي بواسطة ‪G00dspeed‬‏ <‪
***@***.***‬‏>:‬

**Comment by shadihh9** [comment]
i  have problem HTTP server error: listen tcp :8081: bind: address already in use

**Comment by GO0dspeed** [comment]
That indicates another service on your machine is listening on 8081 - try another port.

**Comment by shadihh9** [comment]
i tried other port and still have

**Comment by shadihh9** [comment]
i tried other port and still have

 problem

**Comment by GO0dspeed** [comment]
I made a few updates to try to make the tool easier to use - it should default to the victim port (UDP 631) and default listen on a port (12345) locally. hopefully these help!
